services:

  # notebook:
  #   build: ./notebook
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./notebook:/app
  #     - notebook-data:/app/data
  #     - ./models:/home/jovyan/models
  #   networks:
  #     - aerostream
    # restart: unless-stopped

  # postgre for backend
  postgres_backend:
      image: postgres:15-alpine
      container_name: postgres_backend
      environment:
        POSTGRES_USER: ali
        POSTGRES_PASSWORD: root
        POSTGRES_DB: backend_db
      volumes:
        - postgres_backend_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ali -d backend_db"]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - aerostream
      restart: unless-stopped


  postgres_airflow:
    image: postgres:15-alpine
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - aerostream
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: unless-stopped


  # fastAPI Backend
  backend:
    build: ./backend
    container_name: fastapi_backend
    environment:
      DATABASE_URL: postgresql://ali:root@postgres_backend:5432/backend_db
      API_PORT: 8000
    volumes:
      - ./backend:/app
      - ./models:/app/models
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      postgres_backend:
        condition: service_healthy
    networks:
      - aerostream
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  # Airflow (LocalExecutor)
  airflow:
    build: ./airflow
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=aliali

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow-logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./models:/opt/airflow/models
    networks:
      - aerostream
    depends_on:
      postgres_airflow:
        condition: service_healthy
      backend:
        condition: service_started
    restart: unless-stopped

  streamlit:
    build: ./streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
      - ./models:/app/models
      - ./data:/app/data
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
        - backend
    networks:
      - aerostream
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped

volumes:
  postgres_backend_data:
  postgres_airflow_data:
  airflow-logs:
  notebook-data:

networks:
  aerostream:
    driver: bridge